[package]
name = "nbt"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/Lut99/nbt-rs"
authors = ["Lut99"]
description = "Rust implementation of the NBT binary file format."


[dependencies]
